import { createI18n } from 'vue-i18n'

export const supportedLocales = [
  { code: 'pt-BR', label: 'Português', short: 'PT' },
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'es', label: 'Español', short: 'ES' },
] as const

export type SupportedLocale = typeof supportedLocales[number]['code']
const STORAGE_KEY = 'rea-fed-locale'

function initialLocale(): SupportedLocale {
  const stored = localStorage.getItem(STORAGE_KEY)
  if (supportedLocales.some(item => item.code === stored)) return stored as SupportedLocale
  const browser = navigator.language.toLowerCase()
  if (browser.startsWith('en')) return 'en'
  if (browser.startsWith('es')) return 'es'
  return 'pt-BR'
}

const messages = {
  'pt-BR': {
    common: { loading: 'Carregando…', retry: 'Tentar novamente', cancel: 'Cancelar', save: 'Salvar alterações', search: 'Buscar', update: 'Atualizar', open: 'Abrir', remove: 'Remover', required: 'Obrigatório', pending: 'Pendente', verified: 'Verificado', following: 'Seguindo', follow: 'Seguir', wait: 'Aguarde…', back: 'Voltar', error: 'Erro', notInformed: 'Não informado' },
    language: { label: 'Idioma da interface' },
    nav: { feed: 'Feed', people: 'Pessoas', explore: 'Explorar', platforms: 'Plataformas', verify: 'Verificar', publish: 'Publicar', login: 'Entrar', logout: 'Sair', search: 'Buscar recursos…', searchLabel: 'Buscar recursos', tagline: 'Recursos educacionais abertos em uma rede federada.', demo: 'Frontend demonstrativo · APIs externas' },
    home: { eyebrow: 'Uma rede federada de conhecimento', title: 'Recursos abertos.', titleAccent: 'Conectados pela federação.', lead: 'Siga plataformas educacionais de diferentes instituições e receba suas novas publicações no seu feed. A origem continua explícita e a autoria pode ser verificada.', openFeed: 'Abrir meu feed', discover: 'Descobrir plataformas', networkTitle: 'Uma rede, várias plataformas', networkText: 'Você não precisa visitar cada repositório. Siga uma plataforma e as publicações dela passam a fazer parte do seu feed.', followPlatforms: 'Siga plataformas', receive: 'Receba novas publicações', preserve: 'Preserve a origem federada', verifyAuthorship: 'Verifique a autoria', how: 'Como funciona', flow: 'Da federação ao seu feed', step1: '1. Descubra', step1Text: 'Encontre plataformas participantes da federação e conheça suas comunidades e recursos.', step2: '2. Siga', step2Text: 'Escolha as plataformas que deseja acompanhar. Você controla quais fontes aparecem no seu feed.', step3: '3. Acompanhe', step3Text: 'Novas publicações das plataformas seguidas aparecem em uma timeline única, mantendo sua proveniência.' },
    login: { eyebrow: 'Acessar sua conta', title: 'Entrar no REA.fed', lead: 'Use a conta da sua instância Pleroma. O REA.fed autentica diretamente na instância e não guarda sua senha.', username: 'Usuário', usernamePlaceholder: 'seu_usuario', password: 'Senha', passwordPlaceholder: 'Sua senha', show: 'Mostrar senha', hide: 'Ocultar senha', submitting: 'Autenticando…', submit: 'Entrar', failure: 'Não foi possível entrar', create: 'Criar uma conta', or: 'ou', hint: 'A instância é definida pelo administrador. Sua senha é enviada diretamente por HTTPS e apenas o token de sessão é mantido.' },
    resources: { eyebrow: 'Catálogo local', title: 'Explorar recursos', lead: 'Todos os recursos educacionais publicados localmente nesta instância.', placeholder: 'Busque por título, autor, área, plataforma ou palavra-chave…', label: 'Buscar recursos educacionais', submit: 'Buscar recursos', resultsFor: 'Resultados para:', clear: 'Limpar busca', loading: 'Carregando recursos locais…', loadingHint: 'Mostrando os primeiros resultados assim que a instância responder.', failure: 'Não foi possível carregar os recursos', empty: 'Nenhum recurso encontrado', emptyHint: 'Não encontramos recursos para essa busca. Tente outro título, autor, área ou palavra-chave.', seeAll: 'Ver todos os recursos', found: '{count} recurso encontrado | {count} recursos encontrados', updating: 'Atualizando catálogo local…', loadingMore: 'Carregando mais recursos locais… (página {page})', by: 'por' },
    publish: { eyebrow: 'Publicar no Pleroma', title: 'Novo recurso', lead: 'O arquivo será registrado no IPFS com evidências criptográficas e também anexado a uma nova postagem no Pleroma.', connected: 'Conectado ao Pleroma', connectedBadge: '✓ conectado', active: 'Autorização ativa', activeText: 'O REA.fed usará a autorização concedida nesta instância para enviar o arquivo e criar a postagem.', selectFile: 'Selecione ou arraste seu arquivo', fileHint: 'PDF, documento, imagem, ZIP ou outro arquivo aceito pela instância e pelo serviço IPFS', willSend: 'será enviado ao Pleroma', titleLabel: 'Título *', titlePlaceholder: 'Título do recurso', area: 'Área', areaPlaceholder: 'Ex.: Física', type: 'Tipo', description: 'Descrição', descriptionPlaceholder: 'Texto que acompanhará o arquivo na postagem', tags: 'Tags', tagsPlaceholder: 'física, ensino médio', privacy: 'Privacidade da postagem', public: 'Público', unlisted: 'Não listado', private: 'Somente seguidores', direct: 'Direto', stageIpfs: '1/2 Registrando no IPFS…', stagePleroma: '2/2 Publicando no Pleroma…', stageIpfsText: 'Calculando SHA-256, assinando o manifesto e enviando o recurso para o IPFS.', stagePleromaText: 'O arquivo continua anexado à publicação para manter a compatibilidade com o catálogo federado.', failure: 'Não foi possível publicar', submit: 'Registrar no IPFS e publicar', submitting: 'Preparando recurso…', success: 'Recurso registrado e publicado', successText: 'O arquivo foi armazenado no IPFS, recebeu um manifesto assinado e também foi anexado à postagem do Pleroma.', identity: 'Identidade do recurso', manifest: 'Manifesto', signature: 'Assinatura', timestamp: 'Timestamp', publication: 'Publicação', sent: '✓ enviado', view: 'Ver no Pleroma', back: 'Voltar aos recursos' },
    verify: { eyebrow: 'Verificação pública', title: 'Comprove a autenticidade de um recurso', lead: 'Envie o arquivo original e as evidências fornecidas pela plataforma de origem: manifest.json, .sig e .ots.', what: 'O que será verificado?', whatText: 'O arquivo será comparado ao manifesto, a assinatura será validada e a evidência temporal será conferida.', original: '1. Arquivo original', originalText: 'Envie exatamente o arquivo que deseja autenticar.', choose: 'Escolha um arquivo ou arraste aqui', fileHint: 'PDF, documento, apresentação ou outro recurso publicado', remove: 'Remover arquivo', evidence: '2. Evidências de autoria', evidenceText: 'Envie os arquivos que acompanham o recurso publicado.', selected: '{count}/3 selecionados', selectedFile: 'Arquivo selecionado', selectEvidence: 'Arraste ou clique para selecionar', note: 'Esses arquivos devem ter sido obtidos da plataforma que publicou originalmente o recurso.', submit: 'Verificar autoria e integridade', submitting: 'Verificando evidências…', hint: 'Selecione o arquivo original e as três evidências para habilitar a verificação.', processing: 'Verificando o recurso', processingText: 'A API está comparando o arquivo com as evidências fornecidas.', failure: 'Não foi possível verificar', authentic: 'Arquivo autêntico', authenticText: 'Integridade, assinatura, autoria e evidência temporal foram confirmadas.', altered: 'Arquivo não corresponde à evidência', unconfirmed: 'Verificação não confirmada', integrity: 'Integridade', signature: 'Assinatura', authorship: 'Autoria', timestamp: 'Evidência temporal', confirmed: '✓ Confirmada', notConfirmed: '✕ Não confirmada', valid: '✓ Válida', invalid: '✕ Inválida', verifiable: '✓ Verificável', notVerified: '✕ Não verificada', technical: 'Detalhes técnicos' },
    users: { eyebrow: 'Rede social federada', title: 'Pessoas', lead: 'Pesquise usuários da federação, siga contas e acompanhe seus posts no feed.', placeholder: 'Buscar @usuario ou nome…', searching: 'Buscando…', searchState: 'Pesquisando usuários…', empty: 'Nenhum usuário encontrado.', profile: 'Perfil', yourList: 'Sua lista', following: 'Seguindo', accounts: '{count} conta | {count} contas', loading: 'Carregando contas seguidas…', noFollowing: 'Você ainda não segue nenhum usuário.', noFollowingText: 'Pesquise uma pessoa acima para começar a acompanhar seus posts.', viewProfile: 'Ver perfil →', unfollow: 'Deixar de seguir' },
    feed: { eyebrow: 'Sua rede federada', local: 'Local', localText: 'Posts publicados na instância configurada.', following: 'Seguindo', followingText: 'Posts das pessoas que você segue, incluindo contas remotas.', global: 'Global', globalText: 'Posts públicos conhecidos pela sua instância.', tabs: 'Tipos de feed', loading: 'Carregando publicações…', empty: 'Nenhum post encontrado', followHint: 'Siga usuários para montar seu feed pessoal.', publicEmpty: 'Não há posts públicos disponíveis neste momento.', findPeople: 'Encontrar pessoas', openPost: 'Abrir publicação', attachment: 'Anexo', openAttachment: 'Abrir anexo', network: 'Sua rede', people: '{count} pessoa seguida | {count} pessoas seguidas', networkHint: 'O feed Seguindo usa a timeline inicial da sua conta Pleroma.', manage: 'Gerenciar pessoas' },
    oauth: { title: 'Autenticação', connecting: 'Conectando…', connectingText: 'Estamos concluindo a autorização da sua instância Pleroma.', failure: 'Não foi possível entrar', retry: 'Tentar novamente', missingCode: 'A resposta da instância não contém o código de autorização esperado.' },
  },
  en: {
    common: { loading: 'Loading…', retry: 'Try again', cancel: 'Cancel', save: 'Save changes', search: 'Search', update: 'Refresh', open: 'Open', remove: 'Remove', required: 'Required', pending: 'Pending', verified: 'Verified', following: 'Following', follow: 'Follow', wait: 'Please wait…', back: 'Back', error: 'Error', notInformed: 'Not provided' },
    language: { label: 'Interface language' },
    nav: { feed: 'Feed', people: 'People', explore: 'Explore', platforms: 'Platforms', verify: 'Verify', publish: 'Publish', login: 'Sign in', logout: 'Sign out', search: 'Search resources…', searchLabel: 'Search resources', tagline: 'Open educational resources in a federated network.', demo: 'Demo frontend · External APIs' },
    home: { eyebrow: 'A federated knowledge network', title: 'Open resources.', titleAccent: 'Connected through federation.', lead: 'Follow educational platforms from different institutions and receive new publications in your feed. Origins remain explicit and authorship can be verified.', openFeed: 'Open my feed', discover: 'Discover platforms', networkTitle: 'One network, many platforms', networkText: 'You do not need to visit every repository. Follow a platform and its publications become part of your feed.', followPlatforms: 'Follow platforms', receive: 'Receive new publications', preserve: 'Preserve federated origin', verifyAuthorship: 'Verify authorship', how: 'How it works', flow: 'From federation to your feed', step1: '1. Discover', step1Text: 'Find participating platforms and learn about their communities and resources.', step2: '2. Follow', step2Text: 'Choose the platforms you want to follow. You control which sources appear in your feed.', step3: '3. Keep up', step3Text: 'New publications appear in a single timeline while preserving their provenance.' },
    login: { eyebrow: 'Access your account', title: 'Sign in to REA.fed', lead: 'Use your Pleroma account. REA.fed authenticates directly with the instance and does not store your password.', username: 'Username', usernamePlaceholder: 'your_username', password: 'Password', passwordPlaceholder: 'Your password', show: 'Show password', hide: 'Hide password', submitting: 'Signing in…', submit: 'Sign in', failure: 'Could not sign in', create: 'Create an account', or: 'or', hint: 'The instance is configured by the administrator. Your password is sent directly over HTTPS and only the session token is kept.' },
    resources: { eyebrow: 'Local catalog', title: 'Explore resources', lead: 'All educational resources published locally on this instance.', placeholder: 'Search by title, author, subject, platform or keyword…', label: 'Search educational resources', submit: 'Search resources', resultsFor: 'Results for:', clear: 'Clear search', loading: 'Loading local resources…', loadingHint: 'Showing the first results as soon as the instance responds.', failure: 'Could not load resources', empty: 'No resources found', emptyHint: 'No resources matched this search. Try another title, author, subject or keyword.', seeAll: 'See all resources', found: '{count} resource found | {count} resources found', updating: 'Updating local catalog…', loadingMore: 'Loading more local resources… (page {page})', by: 'by' },
    publish: { eyebrow: 'Publish to Pleroma', title: 'New resource', lead: 'The file will be registered on IPFS with cryptographic evidence and attached to a new Pleroma post.', connected: 'Connected to Pleroma', connectedBadge: '✓ connected', active: 'Authorization active', activeText: 'REA.fed will use this instance authorization to upload the file and create the post.', selectFile: 'Select or drop your file', fileHint: 'PDF, document, image, ZIP or another format accepted by the instance and IPFS service', willSend: 'will be sent to Pleroma', titleLabel: 'Title *', titlePlaceholder: 'Resource title', area: 'Subject', areaPlaceholder: 'E.g. Physics', type: 'Type', description: 'Description', descriptionPlaceholder: 'Text that will accompany the post', tags: 'Tags', tagsPlaceholder: 'physics, high school', privacy: 'Post visibility', public: 'Public', unlisted: 'Unlisted', private: 'Followers only', direct: 'Direct', stageIpfs: '1/2 Registering on IPFS…', stagePleroma: '2/2 Publishing to Pleroma…', stageIpfsText: 'Calculating SHA-256, signing the manifest and uploading the resource to IPFS.', stagePleromaText: 'The file remains attached to keep compatibility with the federated catalog.', failure: 'Could not publish', submit: 'Register on IPFS and publish', submitting: 'Preparing resource…', success: 'Resource registered and published', successText: 'The file was stored on IPFS, received a signed manifest and was attached to the Pleroma post.', identity: 'Resource identity', manifest: 'Manifest', signature: 'Signature', timestamp: 'Timestamp', publication: 'Publication', sent: '✓ sent', view: 'View on Pleroma', back: 'Back to resources' },
    verify: { eyebrow: 'Public verification', title: 'Prove a resource is authentic', lead: 'Upload the original file and the evidence supplied by the source platform: manifest.json, .sig and .ots.', what: 'What will be verified?', whatText: 'The file will be compared with the manifest, the signature validated and the timestamp evidence checked.', original: '1. Original file', originalText: 'Upload the exact file you want to authenticate.', choose: 'Choose a file or drop it here', fileHint: 'PDF, document, presentation or another published resource', remove: 'Remove file', evidence: '2. Authorship evidence', evidenceText: 'Upload the files that accompany the published resource.', selected: '{count}/3 selected', selectedFile: 'File selected', selectEvidence: 'Drop or click to select', note: 'These files must come from the platform that originally published the resource.', submit: 'Verify authorship and integrity', submitting: 'Verifying evidence…', hint: 'Select the original file and all three evidence files to enable verification.', processing: 'Verifying resource', processingText: 'The API is comparing the file with the supplied evidence.', failure: 'Could not verify', authentic: 'Authentic file', authenticText: 'Integrity, signature, authorship and timestamp evidence were confirmed.', altered: 'File does not match the evidence', unconfirmed: 'Verification not confirmed', integrity: 'Integrity', signature: 'Signature', authorship: 'Authorship', timestamp: 'Timestamp evidence', confirmed: '✓ Confirmed', notConfirmed: '✕ Not confirmed', valid: '✓ Valid', invalid: '✕ Invalid', verifiable: '✓ Verifiable', notVerified: '✕ Not verified', technical: 'Technical details' },
    users: { eyebrow: 'Federated social network', title: 'People', lead: 'Search the federation, follow accounts and keep up with their posts.', placeholder: 'Search @username or name…', searching: 'Searching…', searchState: 'Searching users…', empty: 'No users found.', profile: 'Profile', yourList: 'Your list', following: 'Following', accounts: '{count} account | {count} accounts', loading: 'Loading followed accounts…', noFollowing: 'You are not following anyone yet.', noFollowingText: 'Search for someone above to start following their posts.', viewProfile: 'View profile →', unfollow: 'Unfollow' },
    feed: { eyebrow: 'Your federated network', local: 'Local', localText: 'Posts published on the configured instance.', following: 'Following', followingText: 'Posts from people you follow, including remote accounts.', global: 'Global', globalText: 'Public posts known by your instance.', tabs: 'Feed types', loading: 'Loading posts…', empty: 'No posts found', followHint: 'Follow people to build your personal feed.', publicEmpty: 'No public posts are available right now.', findPeople: 'Find people', openPost: 'Open post', attachment: 'Attachment', openAttachment: 'Open attachment', network: 'Your network', people: '{count} person followed | {count} people followed', networkHint: 'The Following feed uses your Pleroma home timeline.', manage: 'Manage people' },
    oauth: { title: 'Authentication', connecting: 'Connecting…', connectingText: 'We are completing authorization with your Pleroma instance.', failure: 'Could not sign in', retry: 'Try again', missingCode: 'The instance response does not contain the expected authorization code.' },
  },
  es: {
    common: { loading: 'Cargando…', retry: 'Intentar de nuevo', cancel: 'Cancelar', save: 'Guardar cambios', search: 'Buscar', update: 'Actualizar', open: 'Abrir', remove: 'Eliminar', required: 'Obligatorio', pending: 'Pendiente', verified: 'Verificado', following: 'Siguiendo', follow: 'Seguir', wait: 'Espere…', back: 'Volver', error: 'Error', notInformed: 'No informado' },
    language: { label: 'Idioma de la interfaz' },
    nav: { feed: 'Inicio', people: 'Personas', explore: 'Explorar', platforms: 'Plataformas', verify: 'Verificar', publish: 'Publicar', login: 'Entrar', logout: 'Salir', search: 'Buscar recursos…', searchLabel: 'Buscar recursos', tagline: 'Recursos educativos abiertos en una red federada.', demo: 'Frontend de demostración · APIs externas' },
    home: { eyebrow: 'Una red federada de conocimiento', title: 'Recursos abiertos.', titleAccent: 'Conectados por la federación.', lead: 'Sigue plataformas educativas de diferentes instituciones y recibe nuevas publicaciones. El origen permanece explícito y la autoría puede verificarse.', openFeed: 'Abrir mi inicio', discover: 'Descubrir plataformas', networkTitle: 'Una red, varias plataformas', networkText: 'No necesitas visitar cada repositorio. Sigue una plataforma y sus publicaciones formarán parte de tu inicio.', followPlatforms: 'Sigue plataformas', receive: 'Recibe nuevas publicaciones', preserve: 'Preserva el origen federado', verifyAuthorship: 'Verifica la autoría', how: 'Cómo funciona', flow: 'De la federación a tu inicio', step1: '1. Descubre', step1Text: 'Encuentra plataformas participantes y conoce sus comunidades y recursos.', step2: '2. Sigue', step2Text: 'Elige las plataformas que deseas seguir. Tú controlas las fuentes.', step3: '3. Acompaña', step3Text: 'Las nuevas publicaciones aparecen en una única línea de tiempo manteniendo su procedencia.' },
    login: { eyebrow: 'Accede a tu cuenta', title: 'Entrar en REA.fed', lead: 'Usa tu cuenta de Pleroma. REA.fed autentica directamente con la instancia y no guarda tu contraseña.', username: 'Usuario', usernamePlaceholder: 'tu_usuario', password: 'Contraseña', passwordPlaceholder: 'Tu contraseña', show: 'Mostrar contraseña', hide: 'Ocultar contraseña', submitting: 'Autenticando…', submit: 'Entrar', failure: 'No fue posible entrar', create: 'Crear una cuenta', or: 'o', hint: 'La instancia es configurada por el administrador. Tu contraseña se envía directamente por HTTPS y solo se conserva el token de sesión.' },
    resources: { eyebrow: 'Catálogo local', title: 'Explorar recursos', lead: 'Todos los recursos educativos publicados localmente en esta instancia.', placeholder: 'Busca por título, autor, área, plataforma o palabra clave…', label: 'Buscar recursos educativos', submit: 'Buscar recursos', resultsFor: 'Resultados para:', clear: 'Limpiar búsqueda', loading: 'Cargando recursos locales…', loadingHint: 'Mostrando los primeros resultados cuando responda la instancia.', failure: 'No fue posible cargar los recursos', empty: 'No se encontraron recursos', emptyHint: 'No encontramos recursos para esta búsqueda. Prueba otro título, autor, área o palabra clave.', seeAll: 'Ver todos los recursos', found: '{count} recurso encontrado | {count} recursos encontrados', updating: 'Actualizando catálogo local…', loadingMore: 'Cargando más recursos locales… (página {page})', by: 'por' },
    publish: { eyebrow: 'Publicar en Pleroma', title: 'Nuevo recurso', lead: 'El archivo se registrará en IPFS con evidencias criptográficas y se adjuntará a una publicación de Pleroma.', connected: 'Conectado a Pleroma', connectedBadge: '✓ conectado', active: 'Autorización activa', activeText: 'REA.fed usará esta autorización para enviar el archivo y crear la publicación.', selectFile: 'Selecciona o arrastra tu archivo', fileHint: 'PDF, documento, imagen, ZIP u otro formato aceptado', willSend: 'se enviará a Pleroma', titleLabel: 'Título *', titlePlaceholder: 'Título del recurso', area: 'Área', areaPlaceholder: 'Ej.: Física', type: 'Tipo', description: 'Descripción', descriptionPlaceholder: 'Texto que acompañará la publicación', tags: 'Etiquetas', tagsPlaceholder: 'física, secundaria', privacy: 'Privacidad de la publicación', public: 'Público', unlisted: 'No listado', private: 'Solo seguidores', direct: 'Directo', stageIpfs: '1/2 Registrando en IPFS…', stagePleroma: '2/2 Publicando en Pleroma…', stageIpfsText: 'Calculando SHA-256, firmando el manifiesto y enviando el recurso a IPFS.', stagePleromaText: 'El archivo sigue adjunto para mantener la compatibilidad con el catálogo federado.', failure: 'No fue posible publicar', submit: 'Registrar en IPFS y publicar', submitting: 'Preparando recurso…', success: 'Recurso registrado y publicado', successText: 'El archivo se almacenó en IPFS, recibió un manifiesto firmado y se adjuntó a la publicación.', identity: 'Identidad del recurso', manifest: 'Manifiesto', signature: 'Firma', timestamp: 'Marca de tiempo', publication: 'Publicación', sent: '✓ enviado', view: 'Ver en Pleroma', back: 'Volver a recursos' },
    verify: { eyebrow: 'Verificación pública', title: 'Comprueba la autenticidad de un recurso', lead: 'Envía el archivo original y las evidencias de la plataforma de origen: manifest.json, .sig y .ots.', what: '¿Qué se verificará?', whatText: 'El archivo se comparará con el manifiesto, se validará la firma y se comprobará la evidencia temporal.', original: '1. Archivo original', originalText: 'Envía exactamente el archivo que deseas autenticar.', choose: 'Elige un archivo o arrástralo aquí', fileHint: 'PDF, documento, presentación u otro recurso publicado', remove: 'Eliminar archivo', evidence: '2. Evidencias de autoría', evidenceText: 'Envía los archivos que acompañan al recurso publicado.', selected: '{count}/3 seleccionados', selectedFile: 'Archivo seleccionado', selectEvidence: 'Arrastra o haz clic para seleccionar', note: 'Estos archivos deben provenir de la plataforma que publicó originalmente el recurso.', submit: 'Verificar autoría e integridad', submitting: 'Verificando evidencias…', hint: 'Selecciona el archivo original y las tres evidencias para habilitar la verificación.', processing: 'Verificando el recurso', processingText: 'La API compara el archivo con las evidencias proporcionadas.', failure: 'No fue posible verificar', authentic: 'Archivo auténtico', authenticText: 'Se confirmaron la integridad, firma, autoría y evidencia temporal.', altered: 'El archivo no coincide con la evidencia', unconfirmed: 'Verificación no confirmada', integrity: 'Integridad', signature: 'Firma', authorship: 'Autoría', timestamp: 'Evidencia temporal', confirmed: '✓ Confirmada', notConfirmed: '✕ No confirmada', valid: '✓ Válida', invalid: '✕ Inválida', verifiable: '✓ Verificable', notVerified: '✕ No verificada', technical: 'Detalles técnicos' },
    users: { eyebrow: 'Red social federada', title: 'Personas', lead: 'Busca usuarios de la federación, sigue cuentas y acompaña sus publicaciones.', placeholder: 'Buscar @usuario o nombre…', searching: 'Buscando…', searchState: 'Buscando usuarios…', empty: 'No se encontraron usuarios.', profile: 'Perfil', yourList: 'Tu lista', following: 'Siguiendo', accounts: '{count} cuenta | {count} cuentas', loading: 'Cargando cuentas seguidas…', noFollowing: 'Todavía no sigues a nadie.', noFollowingText: 'Busca una persona arriba para empezar a seguir sus publicaciones.', viewProfile: 'Ver perfil →', unfollow: 'Dejar de seguir' },
    feed: { eyebrow: 'Tu red federada', local: 'Local', localText: 'Publicaciones de la instancia configurada.', following: 'Siguiendo', followingText: 'Publicaciones de las personas que sigues, incluidas cuentas remotas.', global: 'Global', globalText: 'Publicaciones públicas conocidas por tu instancia.', tabs: 'Tipos de inicio', loading: 'Cargando publicaciones…', empty: 'No se encontraron publicaciones', followHint: 'Sigue personas para crear tu inicio personal.', publicEmpty: 'No hay publicaciones públicas disponibles ahora.', findPeople: 'Encontrar personas', openPost: 'Abrir publicación', attachment: 'Adjunto', openAttachment: 'Abrir adjunto', network: 'Tu red', people: '{count} persona seguida | {count} personas seguidas', networkHint: 'El inicio Siguiendo usa la línea de tiempo inicial de tu cuenta Pleroma.', manage: 'Gestionar personas' },
    oauth: { title: 'Autenticación', connecting: 'Conectando…', connectingText: 'Estamos completando la autorización con tu instancia Pleroma.', failure: 'No fue posible entrar', retry: 'Intentar de nuevo', missingCode: 'La respuesta de la instancia no contiene el código de autorización esperado.' },
  },
}

export const i18n = createI18n({ legacy: false, locale: initialLocale(), fallbackLocale: 'pt-BR', messages })

export function setLocale(locale: SupportedLocale) {
  i18n.global.locale.value = locale
  localStorage.setItem(STORAGE_KEY, locale)
  document.documentElement.lang = locale
}

document.documentElement.lang = i18n.global.locale.value
